### ISSUE TITLE
Add SkinsRestorer proxy / velocity support

### ISSUE THREAD

**Issue by pjindras** [TechnicJelle/BlueMapCustomSkinProvider#3]
Hello, it would be nice, if the plugin had support for skinsrestorer proxy API at least for Velocity proxy.

**Comment by TechnicJelle** [comment]
This plugin will never add support for the SkinsRestorer Java API.
If SkinsRestorer can host a local webserver that provides skins based on UUID or Playername like [Minotar](https://minotar.net/), then this plugin can already make use of that.
I am unsure if it can do that, though.

Someone already forked this plugin and added support for it, though: [Cerothen/BlueMapSkinIntegration](https://github.com/Cerothen/BlueMapSkinIntegration)
