### ISSUE TITLE
add placeholder like "{UUID-}"

### ISSUE THREAD

**Issue by XenWayne** [TechnicJelle/BlueMapCustomSkinProvider#4]
some API prefer UUID without "-"，can u just add a placeholder like {UUID-} which returns a UUID without "-",i saw [BlueMapSkinIntegration](https://github.com/Cerothen/BlueMapSkinIntegration) has that, but it cant load on the server without SkinsRestorer installed,which isn't needed for URL source. thx

**Comment by TechnicJelle** [comment]
Closed by #5
